#!/usr/bin/env ruby
MAJOR_VERSION = 2.0
MINOR_VERSION = 15
BUILD_NUMBER = 2

init_env = ENV['SLOGGER_NO_INITIALIZE'].to_s
ENV['SLOGGER_NO_INITIALIZE'] = "false"

require File.expand_path('../slogger',__FILE__)

ENV['SLOGGER_NO_INITIALIZE'] = init_env
